seed: 42

models:
  separate: False
  policy:
    class: GaussianMixin
    clip_actions: False
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    network:
      - name: net
        input: STATES
        layers: [512, 256, 128]
        activations: elu
    output: ACTIONS
  value:
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [512, 256, 128]
        activations: elu
    output: ONE

memory:
  class: RandomMemory
  memory_size: -1  # auto‑size same as agent:rollouts

agent:
  class: PPO
  rollouts: 128              # horizon_length from RL‑Games
  learning_epochs: 8         # mini_epochs
  mini_batches: 8            # chosen so each batch ≈ rollout/mini_batches
  discount_factor: 0.99      # gamma
  lambda: 0.95               # tau
  learning_rate: 3.0e-4      # learning_rate
  learning_rate_scheduler: KLAdaptiveLR  # adaptive LR schedule
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.008      # kl_threshold
  state_preprocessor: RunningStandardScaler  # normalize_input
  state_preprocessor_kwargs: null
  value_preprocessor: RunningStandardScaler  # normalize_value
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0        # grad_norm
  ratio_clip: 0.2            # e_clip
  value_clip: 0.2            # clip_value
  clip_predicted_values: True
  entropy_loss_scale: 0.01   # entropy_coef
  value_loss_scale: 1.0      # critic_coef
  kl_threshold: 0.008        # early‑stop safeguard
  rewards_shaper_scale: 0.1  # reward_shaper.scale_value
  time_limit_bootstrap: False
  experiment:
    directory: "harold_direct"
    experiment_name: ""
    write_interval: 10
    checkpoint_interval: auto

trainer:
  class: SequentialTrainer
  timesteps: 12800          # horizon_length * max_epochs (128 * 50)
  environment_info: log

