[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "../../../docs/sim/isaac_lab_extension.md"

title = "Harold Isaac Lab"
author = "Matteo"
maintainer = "Matteo"
description="Isaac Lab extension for Harold quadruped robot training"
repository = "https://github.com/isaac-sim/IsaacLab.git"
keywords = ["quadruped", "locomotion", "isaaclab", "reinforcement-learning"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "harold_isaac_lab"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
